; PlatformIO Project Configuration File
;
; LoraMeister - ESP32 LoRa General-Purpose Communication System
;
; HARDWARE: ESP32 DevKit V1 + RYLR890/RYLR896

[platformio]
src_dir = .
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
monitor_filters =
    default
    time
upload_speed = 921600

; OTA partition table
board_build.partitions = default.csv

lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    ZinggJM/GxEPD2 @ ^1.5

[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

monitor_speed = 115200
monitor_filters =
    default
    time
upload_speed = 921600

build_flags =
    -DUSE_XIAO_SX1262=true

lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
