#!/usr/bin/env python3
"""
Convert a monochrome PNG into a GxEPD2/Adafruit-GFX drawBitmap() header.

Usage:
  python artwork/scripts/png_to_epd_bitmap.py \
    --input artwork/source/user_art.png \
    --output artwork/generated/eink_user_art_bitmap.h \
    --symbol EINK_USER_ART_BITMAP
"""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image


def pack_msb_row_major(image: Image.Image) -> bytes:
    width, height = image.size
    packed = bytearray()

    # In mode "1", pixel value 0 = black, 255 = white.
    for y in range(height):
        byte_val = 0
        bit_count = 0
        for x in range(width):
            pixel = image.getpixel((x, y))
            bit = 1 if pixel == 0 else 0
            byte_val = (byte_val << 1) | bit
            bit_count += 1
            if bit_count == 8:
                packed.append(byte_val)
                byte_val = 0
                bit_count = 0

        if bit_count != 0:
            byte_val <<= (8 - bit_count)
            packed.append(byte_val)

    return bytes(packed)


def format_bytes(data: bytes, line_width: int = 12) -> str:
    rows = []
    for i in range(0, len(data), line_width):
        chunk = data[i : i + line_width]
        rows.append("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    return "\n".join(rows)


def generate_header(symbol: str, width: int, height: int, data: bytes) -> str:
    guard = f"{symbol}_H"
    return f"""/* Auto-generated by png_to_epd_bitmap.py */
#ifndef {guard}
#define {guard}

#define EINK_USER_ART_WIDTH {width}
#define EINK_USER_ART_HEIGHT {height}

static const unsigned char {symbol}[] PROGMEM = {{
{format_bytes(data)}
}};

#endif // {guard}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert PNG to e-ink bitmap header")
    parser.add_argument("--input", required=True, help="Input PNG path")
    parser.add_argument("--output", required=True, help="Output header path")
    parser.add_argument("--symbol", default="EINK_USER_ART_BITMAP", help="C symbol name")
    parser.add_argument("--threshold", type=int, default=128, help="Binarization threshold 0-255")
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    img = Image.open(input_path).convert("L")
    bw = img.point(lambda p: 255 if p >= args.threshold else 0, mode="1")

    width, height = bw.size
    packed = pack_msb_row_major(bw)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generate_header(args.symbol, width, height, packed), encoding="utf-8")

    print(f"OK: {input_path} -> {output_path} ({width}x{height}, {len(packed)} bytes)")


if __name__ == "__main__":
    main()
